// frontend/src/main.tsx
import ReactDOM from "react-dom/client";
import { Grommet } from "grommet";
import { createBrowserRouter, Outlet, RouterProvider } from "react-router-dom";
import { Toaster } from "./components/toaster";

import { HomePage } from "./pages/home";
import { SignInPage } from "./pages/signin";
import { SignUpPage } from "./pages/signup";
import { SignoutPage } from "./pages/signout";
import { AddCatPage } from "./pages/add-cat";
import { EditCatPage } from "./pages/edit-cat";
import { ProfilePage } from "./pages/profile";

import { ToasterProvider } from "./components/toaster/provider";
import { AuthenticationProvider } from "./contexts/authentication-provider";
import { CatsProvider } from "./contexts/cats-provider";
import { SessionGuard } from "./containers/session-guard";
import { CatOwnerEditGuard } from "./containers/cat-owner-edit-guard";

import "./index.css";

const router = createBrowserRouter([
  {
    path: "/",

    element: (
      <>
        <HomePage />
        <Outlet />
      </>
    ),
    children: [
      {
        path: "/cats/new",

        element: (
          <SessionGuard>
            <AddCatPage />
          </SessionGuard>
        ),
      },
      {
        path: "/cats/:id/edit",
        element: (
          <SessionGuard>
            <CatOwnerEditGuard>
              <EditCatPage />
            </CatOwnerEditGuard>
          </SessionGuard>
        ),
      },
      {
        path: "/signin",
        element: <SignInPage />,
      },
      {
        path: "/signup",
        element: <SignUpPage />,
      },
      {
        path: "/signout",
        element: <SignoutPage />,
      },
      {
        path: "/profile",
        element: (
          <SessionGuard>
            <ProfilePage />
          </SessionGuard>
        ),
      },
    ],
  },
]);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <Grommet>
    <AuthenticationProvider>
      <CatsProvider>
        <ToasterProvider>
          <RouterProvider router={router} />
          <Toaster />
        </ToasterProvider>
      </CatsProvider>
    </AuthenticationProvider>
  </Grommet>,
);

// frontend-vue/src/main.tsx
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import { App } from './app'
import { HomePage } from '@/pages/home'
import { AddCatPage } from '@/pages/add-cat'
import { EditCatPage } from '@/pages/edit-cat'
import { SignInPage } from '@/pages/signin'
import { SignUpPage } from '@/pages/signup'
import { SignOutPage } from '@/pages/signout'
import { ProfilePage } from '@/pages/profile'

import { SessionGuard } from '@/containers/session-guard'

import './main.css'

const app = createApp(App)

app.use(
  createRouter({
    history: createWebHistory(import.meta.env.BASE_URL),
    routes: [
      {
        path: '/',
        component: HomePage,
        children: [
          {
            path: '/cats/new',
            component: {
              render() {
                return (
                  <SessionGuard>
                    <AddCatPage />
                  </SessionGuard>
                )
              }
            }
          },
          {
            path: '/cats/:id/edit',
            component: {
              render() {
                return (
                  <SessionGuard>
                    <EditCatPage />
                  </SessionGuard>
                )
              }
            }
          },
          {
            path: '/signin',
            component: SignInPage
          },
          {
            path: '/signup',
            component: SignUpPage
          },
          {
            path: '/signout',
            component: SignOutPage
          },
          {
            path: '/profile',
            component: {
              render() {
                return (
                  <SessionGuard>
                    <ProfilePage />
                  </SessionGuard>
                )
              }
            }
          }
        ]
      }
    ]
  })
)
app.mount('#app')
