// frontend/src/pages/edit-cat/edit-cat.tsx
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Modal } from "../../components/modal";
import { PetForm } from "../../components/pet-form";
import { usePetForm } from "../../components/pet-form/use-pet-form";

import { useToasterContext } from "../../components/toaster/toaster-context";
import { useFetchApi } from "../../hooks/use-fetch-api";

import { Age, Cat, Breed } from "@app/types";

export const EditCatPage = () => {
  const fetchApi = useFetchApi();
  const navigation = useNavigate();
  const [ages, setAges] = useState<Age[]>([]);
  const [breeds, setBreeds] = useState<Breed[]>([]);
  const [loadingPhoto, setLoadingPhoto] = useState<boolean>(false);
  const { addToast } = useToasterContext();
  const params = useParams();

  const form = usePetForm({
    onSubmit: () => {},
  });

  const fetchAges = () => {
    fetchApi<Age[]>("/ages").then((data) => {
      setAges(data.data);
    });
  };

  const fetchBreeds = () => {
    fetchApi<Breed[]>("/breeds").then((data) => {
      setBreeds(data.data);
    });
  };

  const fetchCat = () => {
    fetchApi<Cat>(`/cats/${params.id}`).then((data) => {
      console.log("dsdsd", data);
    });
  };

  const onClose = () => {
    navigation(-1);
  };
  const onChangePhoto = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target?.files?.[0];

    if (!file) {
      return;
    }

    setLoadingPhoto(true);
    const formData = new FormData();
    formData.append("file", file);
    formData.append("catId", form.values.id);

    fetchApi<Cat["photo"]>("/photos", "POST", formData, {
      headers: {},
    })
      .then((data) => {
        if (data.data) {
          form.setFieldValue("photo", data.data);
        }
      })
      .catch((error) => {
        addToast({
          type: "error",
          text: error.message,
        });
      })
      .finally(() => {
        setLoadingPhoto(false);
      });
  };

  const onRemovePhoto = () => {
    if (!form.values.photo.key) {
      return;
    }
    setLoadingPhoto(true);

    fetchApi<Cat["photo"]>(
      `/photos/${form.values.photo.key}?catId=${form.values.id}`,
      "DELETE",
    )
      .then(() => {
        form.setFieldValue("photo", initialValues.photo);
        addToast({
          type: "success",
          text: "Photo successfully removed",
        });
      })
      .catch((error) => {
        addToast({
          type: "error",
          text: error.message,
        });
      })
      .finally(() => {
        setLoadingPhoto(false);
      });
  };

  useEffect(() => {
    fetchAges();
    fetchBreeds();
    fetchCat();
  }, []);
  return (
    <Modal title="Edit cat" show onClose={onClose}>
      <PetForm
        {...form}
        ages={ages}
        breeds={breeds}
        loadingPhoto={loadingPhoto}
        onChangePhoto={onChangePhoto}
        onRemovePhoto={onRemovePhoto}
      />
    </Modal>
  );
};

// frontend-vue/src/pages/edit-cat.tsx
import { defineComponent, ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'

import * as Modal from '@/components/modal'
import * as Form from '@/components/cat-form'
import { useFetchApi } from '@/hooks/use-fetch-api'
import { useOnRemovePetHandler } from '@/hooks/use-onremove-pet-handler'
import { useOnSubmitPetFormHandler } from '@/hooks/use-onsubmit-pet-form-handler'
import { useOnChangePhotoHandler } from '@/hooks/use-onchange-photo-handler'
import { useOnRemovePhotoHandler } from '@/hooks/use-onremove-photo-handler'
import { type Cat, type Age, type Breed } from '@app/common/types'

export const EditCatPage = defineComponent({
  setup() {
    const ages = ref<Age[]>([])
    const breeds = ref<Breed[]>([])
    const fetchApi = useFetchApi()
    const router = useRouter()
    const route = useRoute()

    const { petForm, onSubmit } = useOnSubmitPetFormHandler()
    const { onChangePhoto, loading: loadingOnChangePhoto } = useOnChangePhotoHandler({ petForm })
    const { onRemovePhoto, loading: loadingOnRemovePhoto } = useOnRemovePhotoHandler({ petForm })
    const { onRemovePet, loading: loadingOnRemovePet } = useOnRemovePetHandler({ petForm })

    const onCloseModal = () => {
      router.go(-1)
    }

    onMounted(() => {
      Promise.all([
        fetchApi<Age[]>('/ages'),
        fetchApi<Breed[]>('/breeds'),
        fetchApi<Cat>(`/cats/${route.params.id}`)
      ]).then((res) => {
        ages.value = res[0].data
        breeds.value = res[1].data
        petForm.resetForm({
          values: res[2].data
        })
      })
    })

    return () => {
      return (
        <Modal.Root open={true}>
          <Modal.Backdrop />
          <Modal.Content>
            <Modal.Header>
              <Modal.Close onClick={onCloseModal} />
              <Modal.Title>Edit cat</Modal.Title>
            </Modal.Header>
            <Form.Root onSubmit={onSubmit}>
              <Form.Photo
                onChange={onChangePhoto}
                onRemove={onRemovePhoto}
                loading={loadingOnChangePhoto.value || loadingOnRemovePhoto.value}
              />
              <Form.Name />
              <Form.Breed breeds={breeds.value} />
              <Form.Age ages={ages.value} />
              <Form.Description />
              <Form.ActionButtons>
                <Form.Submit />
                <Form.Remove
                  loading={loadingOnRemovePet.value}
                  disabled={loadingOnChangePhoto.value || loadingOnRemovePhoto.value}
                  onClick={onRemovePet}
                />
              </Form.ActionButtons>
            </Form.Root>
          </Modal.Content>
        </Modal.Root>
      )
    }
  },
  name: 'EditCatPage'
})
