// frontend/src/pages/signin.tsx
import { useNavigate } from "react-router-dom";
import { Modal } from "../components/modal";
import { SignInForm } from "../components/signin-form";
import { useSignInForm } from "../components/signin-form/use-signin-form";
import { useAuthenticationContext } from "../contexts/authentication-provider";
import { useToasterContext } from "../components/toaster/provider";
import { useFetchApi } from "../hooks/use-fetch-api";

import { Authentication } from "@app/types";

export const SignInPage = () => {
  const fetchApi = useFetchApi();
  const { setAuthentication } = useAuthenticationContext();
  const { addToast } = useToasterContext();
  const navigation = useNavigate();

  const closeModal = () => {
    navigation("/");
  };

  const form = useSignInForm({
    onSubmit: async (values) => {
      return fetchApi<Authentication>(
        "/auth/signin",
        "POST",
        JSON.stringify(values),
      )
        .then((data) => {
          setAuthentication(data.data);
          addToast({
            text: "Sign in sucessfuly",
            type: "success",
          });
          closeModal();
        })
        .catch((error) => {
          addToast({
            type: "error",
            text: error.message,
          });
        });
    },
  });

  return (
    <Modal title="Sign in" show onClose={closeModal}>
      <SignInForm {...form} />
    </Modal>
  );
};

// frontend-vue/src/pages/signin.tsx
import { defineComponent, watch } from 'vue'
import { useRouter } from 'vue-router'
import * as Modal from '@/components/modal'
import * as Form from '@/components/signin-form'
import { useToaster } from '@/components/toaster'

import { useFetchApi } from '@/hooks/use-fetch-api'
import { useAuthentication } from '@/contexts/authentication-provider'

import { type Authentication } from '@app/common/types'

export const SignInPage = defineComponent({
  setup() {
    const router = useRouter()
    const form = Form.useSignInForm()
    const toaster = useToaster()
    const auth = useAuthentication()
    const fetchApi = useFetchApi()

    const onSubmit = form.handleSubmit(async (values) => {
      return fetchApi<Authentication>('/auth/signin', 'POST', JSON.stringify(values))
        .then((data) => {
          if (auth) {
            auth.value.authentication = data.data
          }

          toaster?.value.addToast({
            text: 'Sign in sucessfuly',
            type: 'success'
          })
          onCloseModal()
        })
        .catch((error) => {
          toaster?.value.addToast({
            type: 'error',
            text: error.message
          })
        })
    })
    const onCloseModal = () => {
      router.push('/')
    }

    return () => {
      return (
        <Modal.Root open={true}>
          <Modal.Backdrop />
          <Modal.Content>
            <Modal.Header>
              <Modal.Close onClick={onCloseModal} />
              <Modal.Title>Sign In</Modal.Title>
            </Modal.Header>
            <Form.Root onSubmit={onSubmit}>
              <Form.Email />
              <Form.Password />
              <Form.Submit />
            </Form.Root>
          </Modal.Content>
        </Modal.Root>
      )
    }
  }
})
