// frontend/src/pages/signup.tsx
import { useNavigate } from "react-router-dom";

import { Modal } from "../components/modal";
import { SignUpForm, useSignUpForm } from "../components/signup-form";

import { useToasterContext } from "../components/toaster/provider";
import { useAuthenticationContext } from "../contexts/authentication-provider";
import { useFetchApi } from "../hooks/use-fetch-api";

import { Authentication } from "@app/types";

export const SignUpPage = () => {
  const fetchApi = useFetchApi();
  const { setAuthentication } = useAuthenticationContext();
  const { addToast } = useToasterContext();

  const navigation = useNavigate();

  const onCloseModal = () => {
    navigation("/");
  };

  const form = useSignUpForm({
    onSubmit: async (values) => {
      return fetchApi<Authentication>(
        "/auth/signup",
        "POST",
        JSON.stringify(values),
      )
        .then((data) => {
          setAuthentication(data.data);
          addToast({
            text: "Sign up sucessfuly",
            type: "success",
          });
          onCloseModal();
        })
        .catch((err) => {
          addToast({
            text: err.message,
            type: "error",
          });
        });
    },
  });

  return (
    <Modal.Root show>
      <Modal.Backdrop />
      <Modal.Content>
        <Modal.Header>
          <Modal.Close onClick={onCloseModal} />
          <Modal.Title>Sign Up</Modal.Title>
        </Modal.Header>
        <SignUpForm.Root {...form}>
          <SignUpForm.Name />
          <SignUpForm.Email />
          <SignUpForm.Password />
          <SignUpForm.RepeatPassword />
          <SignUpForm.Submit />
        </SignUpForm.Root>
      </Modal.Content>
    </Modal.Root>
  );
};

// frontend-vue/src/pages/signup.tsx
import { defineComponent } from 'vue'
import { useRouter } from 'vue-router'
import * as Modal from '@/components/modal'
import * as Form from '@/components/signup-form'
import { useToaster } from '@/components/toaster'

import { useFetchApi } from '@/hooks/use-fetch-api'
import { useAuthentication } from '@/contexts/authentication-provider'

import { type Authentication } from '@app/common/types'

export const SignUpPage = defineComponent({
  setup() {
    const router = useRouter()
    const form = Form.useSignInForm()
    const toaster = useToaster()
    const auth = useAuthentication()
    const fetchApi = useFetchApi()

    const onCloseModal = () => {
      router.push('/')
    }

    const onSubmit = form.handleSubmit(async (values) => {
      return fetchApi<Authentication>('/auth/signup', 'POST', JSON.stringify(values))
        .then((data) => {
          if (auth) {
            auth.value.authentication = data.data
          }

          toaster?.value.addToast({
            text: 'Sign up sucessfuly',
            type: 'success'
          })
          onCloseModal()
        })
        .catch((error) => {
          toaster?.value.addToast({
            type: 'error',
            text: error.message
          })
        })
    })

    return () => {
      return (
        <Modal.Root open={true}>
          <Modal.Backdrop />
          <Modal.Content>
            <Modal.Header>
              <Modal.Close onClick={onCloseModal} />
              <Modal.Title>Sign Up</Modal.Title>
            </Modal.Header>
            <Form.Root onSubmit={onSubmit}>
              <Form.Name />
              <Form.Email />
              <Form.Password />
              <Form.RepeatPassword />
              <Form.Submit />
            </Form.Root>
          </Modal.Content>
        </Modal.Root>
      )
    }
  }
})
