// frontend-vue/src/components/field.tsx
import { defineComponent, type VNode, type PropType, type SlotsType, type SetupContext } from 'vue'
export const Field = defineComponent({
  setup({ label, errorMessage }, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    return () => (
      <div>
        {label && <span class="mb-2 block">{label}</span>}
        {slots.default?.()}
        {errorMessage && <p class="mt-2 text-sm text-red-600">{errorMessage}</p>}
      </div>
    )
  },
  props: {
    errorMessage: {
      type: Object as PropType<VNode>,
      required: false
    },
    label: {
      type: String,
      required: false
    }
  }
})

// frontend/src/components/Field.tsx
type Props = {
  label: string;
  errorMessage?: string;
  invalid: boolean;
  children: React.ReactNode;
};
export const Field = ({ label, errorMessage, invalid, children }: Props) => {
  return (
    <div className="block">
      {label && <span className="mb-2 block text-sm">{label}</span>}
      {children}
      {invalid && <span className="text-xs text-red-500">{errorMessage}</span>}
    </div>
  );
};
