// frontend-vue/src/components/password-form/index.tsx
import { defineComponent, type PropType, type SlotsType, type SetupContext } from 'vue'
import { useForm, useField, ErrorMessage, useIsSubmitting } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/yup'
import * as Yup from 'yup'
import ArrowPathIcon from '@heroicons/vue/24/solid/ArrowPathIcon'
import { Field } from '@/components/field'
import { InputPassword } from '@/components/input-password'

export type Values = {
  password: string
  newPassword: string
}

const Schema = toTypedSchema(
  Yup.object({
    password: Yup.string().required(''),
    newPassword: Yup.string().required('')
  })
)

export const Root = defineComponent({
  setup({ onSubmit }, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    return () => (
      <form onSubmit={onSubmit} class="space-y-4">
        <p class="text-gray-600">Change password</p>
        {slots.default?.()}
      </form>
    )
  },
  props: {
    onSubmit: {
      type: Function as PropType<(e: Event) => void>,
      required: true
    }
  }
})

export const Password = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('password')
    return () => (
      <Field label="Password" errorMessage={<ErrorMessage name="password" />}>
        {() => {
          return <InputPassword value={value.value} onChange={handleChange} onBlur={handleBlur} />
        }}
      </Field>
    )
  }
})

export const NewPassword = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('newPassword')
    return () => (
      <Field label="New password" errorMessage={<ErrorMessage name="newPassword" />}>
        {() => {
          return <InputPassword value={value.value} onChange={handleChange} onBlur={handleBlur} />
        }}
      </Field>
    )
  }
})

export const Submit = defineComponent({
  setup() {
    const isSubmitting = useIsSubmitting()

    return () => (
      <button
        type="submit"
        disabled={isSubmitting.value}
        class="flex items-center rounded-md bg-green-700 px-7 py-3 text-white disabled:opacity-70"
      >
        {isSubmitting.value && <ArrowPathIcon class="mr-2 h-4 w-4 animate-spin" />}
        Save
      </button>
    )
  }
})

export function usePasswordForm() {
  return useForm<Values>({
    initialValues: {
      password: '',
      newPassword: ''
    },
    validationSchema: Schema
  })
}

// frontend-react/src/components/password-form/index.tsx
import {
  FormikProvider,
  useFormik,
  FormikConfig,
  useFormikContext,
} from "formik";
import * as Yup from "yup";
import { Field } from "../field";
import { InputPassword } from "../input-password";
import ArrowPathIcon from "@heroicons/react/24/solid/ArrowPathIcon";

export const PasswordForm = {
  Root,
  Password,
  NewPassword,
  Submit,
};

const PasswordFormSchema = Yup.object({
  password: Yup.string().required(""),
  newPassword: Yup.string().required(""),
});

type PasswordFormValues = {
  password: string;
  newPassword: string;
};

function Root({
  children,
  ...rest
}: React.PropsWithChildren<ReturnType<typeof usePasswordForm>>) {
  return (
    <FormikProvider value={rest}>
      <form className="space-y-4" onSubmit={rest.handleSubmit}>
        <p className="text-gray-600">Change password</p>
        {children}
      </form>
    </FormikProvider>
  );
}

function Password() {
  return (
    <Field<PasswordFormValues["password"]> name="password" label="Password">
      {({ field, form }) => {
        return (
          <InputPassword
            name={field.name}
            disabled={form.isSubmitting}
            value={field.value}
            onChange={field.onChange}
            onBlur={field.onBlur}
          />
        );
      }}
    </Field>
  );
}

function NewPassword() {
  return (
    <Field<PasswordFormValues["newPassword"]>
      name="newPassword"
      label="New password"
    >
      {({ field, form }) => {
        return (
          <InputPassword
            name={field.name}
            disabled={form.isSubmitting}
            onPaste={(e) => e.preventDefault()}
            value={field.value}
            onChange={field.onChange}
            onBlur={field.onBlur}
          />
        );
      }}
    </Field>
  );
}

function Submit() {
  const { isSubmitting, dirty, isValid } = useFormikContext();

  return (
    <button
      type="submit"
      disabled={isSubmitting || !dirty || !isValid}
      className="flex items-center rounded-md  border border-gray-200 bg-green-700  px-5 py-2 font-medium text-white disabled:opacity-50"
    >
      {isSubmitting && <ArrowPathIcon className="h-5 w-5" />}
      <span>Save</span>
    </button>
  );
}

export function usePasswordForm({
  onSubmit,
}: Pick<FormikConfig<PasswordFormValues>, "onSubmit">) {
  return useFormik<PasswordFormValues>({
    initialValues: {
      password: "",
      newPassword: "",
    },
    onSubmit,
    validationSchema: PasswordFormSchema,
    validateOnBlur: true,
    validateOnChange: false,
  });
}
