// frontend-vue/src/components/signup-form/index.tsx
import { defineComponent, type PropType, type SlotsType, type SetupContext } from 'vue'
import { useForm, useField, useIsSubmitting, ErrorMessage } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/yup'
import * as Yup from 'yup'
import ArrowPathIcon from '@heroicons/vue/24/solid/ArrowPathIcon'
import { Field } from '@/components/field'
import { InputPassword } from '@/components/input-password'

export type Values = {
  name: string
  email: string
  password: string
  repeatPassword: string
}

const Schema = toTypedSchema(
  Yup.object({
    name: Yup.string().required('This field is required'),
    email: Yup.string().email('Must be a valid email.').required('Email is required'),
    password: Yup.string()
      .required('This field is required')
      .oneOf([Yup.ref('repeatPassword')], 'Passwords must match'),
    repeatPassword: Yup.string()
      .required('This field is required')
      .oneOf([Yup.ref('password')], 'Passwords must match')
  })
)

export const Root = defineComponent({
  setup({ onSubmit }, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    return () => (
      <form onSubmit={onSubmit} class="space-y-4">
        {slots.default?.()}
      </form>
    )
  },
  props: {
    onSubmit: {
      type: Function as PropType<(e: Event) => void>,
      required: true
    }
  }
})

export const Name = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('name')

    return () => (
      <Field label="Name" errorMessage={<ErrorMessage name="name" />}>
        {() => {
          return (
            <input
              value={value.value}
              onChange={handleChange}
              onBlur={handleBlur}
              class="h-12 w-full rounded-md border border-gray-300 px-4 disabled:bg-gray-100 disabled:opacity-70"
            />
          )
        }}
      </Field>
    )
  }
})

export const Email = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('email')

    return () => (
      <Field label="Email" errorMessage={<ErrorMessage name="email" />}>
        {() => {
          return (
            <input
              value={value.value}
              onChange={handleChange}
              onBlur={handleBlur}
              class="h-12 w-full rounded-md border border-gray-300 px-4 disabled:bg-gray-100 disabled:opacity-70"
            />
          )
        }}
      </Field>
    )
  }
})

export const Password = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('password')
    return () => (
      <Field label="Password" errorMessage={<ErrorMessage name="password" />}>
        {() => {
          return <InputPassword value={value.value} onChange={handleChange} onBlur={handleBlur} />
        }}
      </Field>
    )
  }
})

export const RepeatPassword = defineComponent({
  setup() {
    const { value, handleChange, handleBlur } = useField('repeatPassword')
    return () => (
      <Field label="Password" errorMessage={<ErrorMessage name="repeatPassword" />}>
        {() => {
          return (
            <InputPassword
              value={value.value}
              onChange={handleChange}
              onBlur={handleBlur}
              onPaste={(e) => e.preventDefault()}
            />
          )
        }}
      </Field>
    )
  }
})

export const Submit = defineComponent({
  setup() {
    const isSubmitting = useIsSubmitting()

    return () => (
      <button
        type="submit"
        disabled={isSubmitting.value}
        class="flex items-center rounded-md bg-green-700 px-7 py-3 text-white disabled:opacity-70"
      >
        {isSubmitting.value && <ArrowPathIcon class="mr-2 h-4 w-4 animate-spin" />}
        Sign in
      </button>
    )
  }
})

export function useSignInForm() {
  return useForm<Values>({
    initialValues: {
      name: '',
      email: '',
      password: '',
      repeatPassword: ''
    },
    validationSchema: Schema
  })
}

// frontend/src/components/signup-form/signup-form.tsx
import { FormikProvider } from "formik";
import ArrowPathIcon from "@heroicons/react/24/solid/ArrowPathIcon";

import { Name } from "./fields/name";
import { Email } from "./fields/email";
import { Password } from "./fields/password";
import { RepeatPassword } from "./fields/repeat-password";

import { useSignUpForm } from "./use-signup-form";

export type Props = ReturnType<typeof useSignUpForm>;

export const SignUpForm = (props: Props) => {
  return (
    <div className="space-y-8">
      <FormikProvider value={props}>
        <form className="space-y-4" onSubmit={props.handleSubmit}>
          <Name />
          <Email />
          <Password />
          <RepeatPassword />
          <button
            type="submit"
            disabled={props.isSubmitting || !props.dirty}
            className="flex items-center rounded-md  bg-green-700 px-7 py-3 text-white disabled:opacity-70"
          >
            {props.isSubmitting && (
              <ArrowPathIcon className="mr-2 h-4 w-4 animate-spin" />
            )}
            Sign up
          </button>
        </form>
      </FormikProvider>
    </div>
  );
};
