// frontend-vue/src/containers/session-guard.tsx
import { defineComponent, type SlotsType, type SetupContext } from 'vue'
import { useRouter } from 'vue-router'
import { Loader } from '@/components/loader'
import { UnathorizedModal } from '@/components/unauthorized-modal'
import { useAuthentication } from '@/contexts/authentication-provider'

export const SessionGuard = defineComponent({
  setup(_, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    const auth = useAuthentication()
    const router = useRouter()

    const onClose = () => {
      router.go(-1)
    }

    return () => {
      if (auth?.value.authenticating) {
        return <Loader />
      }

      if (!auth?.value.authenticating && !auth?.value.authentication.Username) {
        return <UnathorizedModal onClose={onClose} />
      }
      return slots.default?.()
    }
  }
})

// frontend/src/containers/session-guard.tsx
import { useNavigate } from "react-router-dom";
import { UnathorizedModal } from "../components/unathorized-modal";
import { Loader } from "../components/loader";
import { useAuthenticationContext } from "../contexts/authentication-provider";

type Props = {
  children: React.ReactNode;
};

export const SessionGuard = ({ children }: Props) => {
  const { authenticating, authentication } = useAuthenticationContext();
  const navigate = useNavigate();

  const onClose = () => {
    navigate("/");
  };

  if (authenticating) {
    return <Loader />;
  }

  if (!authenticating && !authentication.Username) {
    return <UnathorizedModal onClose={onClose} />;
  }
  return children;
};
