// frontend/src/pages/profile.tsx
import { useNavigate } from "react-router-dom";
import { Modal } from "../components/modal";
import { ProfileForm } from "../components/profile-form";
import { useProfileForm } from "../components/profile-form/use-profile-form";
import { usePasswordForm } from "../components/profile-form/use-password-form";

export const ProfilePage = () => {
  const navigation = useNavigate();

  const profileForm = useProfileForm({
    onSubmit: () => {},
  });

  const passwordForm = usePasswordForm({
    onSubmit: () => {},
  });

  const onCloseModal = () => {
    navigation("/");
  };

  return (
    <Modal show title="Edit profile" onClose={onCloseModal}>
      <ProfileForm profileForm={profileForm} passwordForm={passwordForm} />
    </Modal>
  );
};

// frontend-vue/src/pages/profile/index.tsx
import { defineComponent, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import * as Modal from '@/components/modal'
import { PasswordForm } from './password-form'
import { ProfileForm } from './profile-form'
export const ProfilePage = defineComponent({
  setup() {
    const router = useRouter()

    const onCloseModal = () => {
      router.push('/')
    }

    return () => {
      return (
        <Modal.Root open={true}>
          <Modal.Backdrop />
          <Modal.Content>
            <Modal.Header>
              <Modal.Close onClick={onCloseModal} />
              <Modal.Title>Edit profile</Modal.Title>
            </Modal.Header>
            <div class="space-y-4">
              <ProfileForm />
              <PasswordForm />
            </div>
          </Modal.Content>
        </Modal.Root>
      )
    }
  }
})
