// frontend-react/src/components/cats-list.tsx
import { Loader } from "./loader";

export const CatsList = {
  Root,
  Body,
  Empty,
  Loading,
};

function Root({ children }: React.PropsWithChildren) {
  return <div className="relative z-0 min-h-[800px]">{children}</div>;
}

function Body({ children }: React.PropsWithChildren) {
  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{children}</div>
  );
}

function Loading() {
  return (
    <div className="absolute w-full bg-red-200">
      <Loader className="absolute" />
    </div>
  );
}

function Empty() {
  return <p className="text-center text-gray-600">No cats to show</p>;
}

// frontend-vue/src/components/cats-list/index.tsx
import { defineComponent, type SetupContext, type SlotsType } from 'vue'
import { Loader } from '@/components/loader'

export const Root = defineComponent({
  setup(_, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    return () => {
      return <div class="relative z-0 min-h-[800px]">{slots.default?.()}</div>
    }
  }
})

export const Body = defineComponent({
  setup(_, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    return () => {
      return <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{slots.default?.()}</div>
    }
  }
})

export function Empty() {
  return <p class="text-center text-gray-600">No cats to show</p>
}
