// frontend/src/contexts/authentication-provider.tsx
import { createContext, useContext, useEffect, useState } from "react";
import { Authentication } from "@app/types";
import {
  getAuthFromStorage,
  setAuthToStorage,
} from "../services/authentication-storage";

import { fetchApi } from "../services/fetch-api";

export type AuthenticationContext = {
  authentication: Authentication;
  authenticating: boolean;
  authenticated: boolean;
  setAuthentication: (authentication: Authentication) => void;
  setAuthenticating: (authenticating: boolean) => void;
  setAuthenticated: (authenticated: boolean) => void;
};

const AuthenticationContext = createContext({} as AuthenticationContext);

type Props = {
  children: React.ReactNode;
};

export const AuthenticationProvider = ({ children }: Props) => {
  const [authentication, setAuthentication] = useState<Authentication>(
    getAuthFromStorage(),
  );
  const [authenticating, setAuthenticating] = useState<boolean>(true);
  const [authenticated, setAuthenticated] = useState(false);

  const value = {
    authentication,
    authenticating,
    authenticated,
    setAuthentication,
    setAuthenticating,
    setAuthenticated,
  };

  useEffect(() => {
    const fetchMe = async () => {
      try {
        setAuthenticating(true);

        const res = await fetchApi("/me");

        if (res.status === 401) {
          setAuthenticated(false);
          setAuthentication({});
          return;
        }

        const json = await res.json();

        setAuthenticated(true);
        setAuthentication({
          ...authentication,
          UserAttributes: json.data,
        });
      } finally {
        setAuthenticating(false);
      }
    };

    fetchMe();
  }, []);

  useEffect(() => {
    setAuthToStorage(authentication);
  }, [authentication]);

  return (
    <AuthenticationContext.Provider value={value}>
      {children}
    </AuthenticationContext.Provider>
  );
};

export const useAuthenticationContext = () => useContext(AuthenticationContext);

// frontend-vue/src/contexts/authentication-provider.tsx
import {
  defineComponent,
  ref,
  type Ref,
  type SlotsType,
  type SetupContext,
  provide,
  inject,
  watch,
  onMounted
} from 'vue'
import { type Authentication } from '@app/types'

import { getAuthFromStorage, setAuthToStorage } from '@app/common/utils/authentication-storage'
import { fetchApi } from '@app/common/utils/fetch-api'

export type AuthenticationContext = {
  authentication: Authentication
  authenticating: boolean
}

export const AuthenticationProvider = defineComponent({
  setup(_, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    const context = ref<AuthenticationContext>({
      authenticating: true,
      authentication: getAuthFromStorage()
    })

    provide('authentication', context)

    watch(
      () => context.value.authentication,
      (authentication) => {
        setAuthToStorage(authentication)
      }
    )

    onMounted(async () => {
      try {
        context.value.authenticating = true
        const res = await fetchApi('/me')

        if (res.status === 401) {
          context.value.authentication = {}
          return
        }
        const json = await res.json()
        context.value.authentication = {
          ...context.value.authentication,
          ...json.data
        }
      } finally {
        context.value.authenticating = false
      }
    })

    return () => <div>{slots.default?.()}</div>
  }
})

export function useAuthentication() {
  return inject<Ref<AuthenticationContext>>('authentication')
}
