// frontend-react/src/contexts/cats-provider.tsx
import { createContext, useContext, useState } from "react";
import { useFetchApi } from "../hooks/use-fetch-api";
import { Cat } from "@app/types";

type CatsContext = {
  cats: Cat[];
  loading: boolean;
  fetchCats: () => void;
};

const CatsContext = createContext({} as CatsContext);

type Props = {
  children: React.ReactElement;
};

export const CatsProvider = ({ children }: Props) => {
  const [cats, setCats] = useState<Cat[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const fetchApi = useFetchApi();

  const fetchCats = () => {
    setLoading(true);
    fetchApi<Cat[]>("/cats")
      .then((data) => {
        setCats(data.data);
      })
      .finally(() => {
        setLoading(false);
      });
  };

  const value = {
    cats,
    loading,
    fetchCats,
  };

  return <CatsContext.Provider value={value}>{children}</CatsContext.Provider>;
};

export const useCatsContext = () => useContext(CatsContext);

// frontend-vue/src/contexts/cats-provider.tsx
import {
  defineComponent,
  ref,
  type Ref,
  type SlotsType,
  type SetupContext,
  provide,
  inject
} from 'vue'

import { useFetchApi } from '@/hooks/use-fetch-api'
import { type Cat } from '@app/common/types'

type CatsContext = {
  cats: Cat[]
  loading: boolean
  fetchCats: () => void
}

export const CatsProvider = defineComponent({
  setup(_, { slots }: SetupContext<{}, SlotsType<{ default?: () => any }>>) {
    const cats = ref<Cat[]>([])
    const loading = ref<boolean>(false)
    const fetchApi = useFetchApi()

    const fetchCats = () => {
      loading.value = true
      fetchApi<Cat[]>('/cats')
        .then((data) => {
          cats.value = data.data
        })
        .finally(() => {
          loading.value = false
        })
    }

    const context = ref({
      cats,
      loading,
      fetchCats
    })

    provide('cats', context)

    return () => <div>{slots.default?.()}</div>
  }
})

export function useCats() {
  return inject<Ref<CatsContext>>('cats')
}
