// frontend-vue/src/pages/edit-cat.tsx
import { defineComponent, ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'

import * as Modal from '@/components/modal'
import * as Form from '@/components/cat-form'
import { useFetchApi } from '@/hooks/use-fetch-api'
import { useOnRemovePetHandler } from '@/hooks/use-onremove-pet-handler'
import { useOnSubmitPetFormHandler } from '@/hooks/use-onsubmit-pet-form-handler'
import { useOnChangePhotoHandler } from '@/hooks/use-onchange-photo-handler'
import { useOnRemovePhotoHandler } from '@/hooks/use-onremove-photo-handler'
import { type Cat, type Age, type Breed } from '@app/common/types'

export const EditCatPage = defineComponent({
  setup() {
    const ages = ref<Age[]>([])
    const breeds = ref<Breed[]>([])
    const fetchApi = useFetchApi()
    const router = useRouter()
    const route = useRoute()

    const { petForm, onSubmit } = useOnSubmitPetFormHandler()
    const { onChangePhoto, loading: loadingOnChangePhoto } = useOnChangePhotoHandler({ petForm })
    const { onRemovePhoto, loading: loadingOnRemovePhoto } = useOnRemovePhotoHandler({ petForm })
    const { onRemovePet, loading: loadingOnRemovePet } = useOnRemovePetHandler({ petForm })

    const onCloseModal = () => {
      router.go(-1)
    }

    onMounted(() => {
      Promise.all([
        fetchApi<Age[]>('/ages'),
        fetchApi<Breed[]>('/breeds'),
        fetchApi<Cat>(`/cats/${route.params.id}`)
      ]).then((res) => {
        ages.value = res[0].data
        breeds.value = res[1].data
        petForm.resetForm({
          values: res[2].data
        })
      })
    })

    return () => {
      return (
        <Modal.Root open={true}>
          <Modal.Backdrop />
          <Modal.Content>
            <Modal.Header>
              <Modal.Close onClick={onCloseModal} />
              <Modal.Title>Edit cat</Modal.Title>
            </Modal.Header>
            <Form.Root onSubmit={onSubmit}>
              <Form.Photo
                onChange={onChangePhoto}
                onRemove={onRemovePhoto}
                loading={loadingOnChangePhoto.value || loadingOnRemovePhoto.value}
              />
              <Form.Name />
              <Form.Breed breeds={breeds.value} />
              <Form.Age ages={ages.value} />
              <Form.Description />
              <Form.ActionButtons>
                <Form.Submit />
                <Form.Remove
                  loading={loadingOnRemovePet.value}
                  disabled={loadingOnChangePhoto.value || loadingOnRemovePhoto.value}
                  onClick={onRemovePet}
                />
              </Form.ActionButtons>
            </Form.Root>
          </Modal.Content>
        </Modal.Root>
      )
    }
  },
  name: 'EditCatPage'
})

// frontend-react/src/pages/edit-cat.tsx
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { Modal } from "../components/modal";
import { CatForm } from "../components/cat-form";

import { useFetchApi } from "../hooks/use-fetch-api";
import { useOnChangePhotoHandler } from "../hooks/use-onchange-photo-handler";
import { useOnRemovePhotoHandler } from "../hooks/use-onremove-photo-handler";
import { useOnSubmitPetFormHandler } from "../hooks/use-onsubmit-pet-form-handler";
import { useOnRemoveCatHandler } from "../hooks/use-onremove-cat-handler";

import { Age, Cat, Breed } from "@app/types";

export const EditCatPage = () => {
  const [ages, setAges] = useState<Age[]>([]);
  const [breeds, setBreeds] = useState<Breed[]>([]);

  const fetchApi = useFetchApi();
  const navigation = useNavigate();
  const params = useParams();

  const petForm = useOnSubmitPetFormHandler();

  const { onRemove, loading: loadingOnRemoveCat } = useOnRemoveCatHandler({
    petForm,
  });

  const { loading: loadingOnChangePhoto, onChangePhoto } =
    useOnChangePhotoHandler({
      petForm,
    });

  const { loading: loadingOnRemovePhoto, onRemovePhoto } =
    useOnRemovePhotoHandler({
      petForm,
    });

  const onCloseModal = () => {
    navigation(-1);
  };

  useEffect(() => {
    Promise.all([
      fetchApi<Age[]>("/ages"),
      fetchApi<Breed[]>("/breeds"),
      fetchApi<Cat>(`/cats/${params.id}`),
    ]).then((res) => {
      setAges(res[0].data);
      setBreeds(res[1].data);
      petForm.resetForm({
        values: res[2].data,
      });
    });
  }, []);

  return (
    <Modal.Root show>
      <Modal.Backdrop />
      <Modal.Content>
        <Modal.Header>
          <Modal.Close onClick={onCloseModal} />
          <Modal.Title>Edit cat</Modal.Title>
        </Modal.Header>
        <CatForm.Root {...petForm}>
          <CatForm.Photo
            loading={loadingOnChangePhoto || loadingOnRemovePhoto}
            onChange={onChangePhoto}
            onRemove={onRemovePhoto}
          />
          <CatForm.Name />
          <CatForm.Age ages={ages} />
          <CatForm.Breed breeds={breeds} />
          <CatForm.Description editor={petForm.editor} />
          <CatForm.ActionButtons>
            <CatForm.Submit />
            <CatForm.Remove
              onClick={onRemove}
              loading={loadingOnRemoveCat}
              disabled={loadingOnChangePhoto || loadingOnRemovePhoto}
            />
          </CatForm.ActionButtons>
        </CatForm.Root>
      </Modal.Content>
    </Modal.Root>
  );
};
