// frontend-vue/src/pages/signout.tsx
import { defineComponent, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthentication } from '@/contexts/authentication-provider'

export const SignOutPage = defineComponent({
  setup() {
    const auth = useAuthentication()
    const router = useRouter()
    onMounted(() => {
      if (auth) {
        auth.value.authentication = {}
        router.push('/')
      }
    })

    return () => {
      return null
    }
  }
})

// frontend-react/src/pages/signout.tsx
import { useEffect } from "react";
import { Navigate } from "react-router-dom";

import { useAuthenticationContext } from "../contexts/authentication-provider";

export const SignoutPage = () => {
  const { setAuthentication } = useAuthenticationContext();

  useEffect(() => {
    setAuthentication({});
  }, []);

  return <Navigate to="/" />;
};
